### ISSUE TITLE
Approve is not a function

### ISSUE THREAD

**Issue by Sam-Devs** [Idle-Labs/idle-contracts#27]
I was running a sample code using the IdleToken ABI and I encountered an error.
I need some clarification.
The mintIdleToken method requires a user should call approve on the underlying asset used (eg. DAI) to allow IdleToken contract to spend _amount of tokens before calling this method before calling but it returned 
```
require("dotenv").config();
const Web3 = require("web3");
const idleTokenABI = require("./abis/IdleTokens.json");
const {
  IdleDAI_BEST,
  IdleRAI_BEST,
  IdleSUSD_BEST,
  IdleTUSD_BEST,
  IdleUSDC_BEST,
  IdleUSDT_BEST,
  IdleWBTC_BEST,
  IdleWETH_BEST,
} = require("./token-addresses/best-yield/mainnet.json");
const {
  IdleDAI_RISK,
  IdleUSDC_RISK,
  IdleUSDT_RISK,
} = require("./token-addresses/risk-adjusted/mainnet.json");

const provider = process.env.KOVAN;

const web3 = new Web3(provider);
const user = "0x9C0cEC1f95582100b07581efCEB45A96FE01e8C0";
// Best-Adjusted
const idleTokenBestDAI = new web3.eth.Contract(idleTokenABI, IdleDAI_BEST);
const idleTokenBestRAI = new web3.eth.Contract(idleTokenABI, IdleRAI_BEST);
const idleTokenBestSUSD = new web3.eth.Contract(idleTokenABI, IdleSUSD_BEST);
const idleTokenBestTUSD = new web3.eth.Contract(idleTokenABI, IdleTUSD_BEST);
const idleTokenBestUSDC = new web3.eth.Contract(idleTokenABI, IdleUSDC_BEST);
const idleTokenBestUSDT = new web3.eth.Contract(idleTokenABI, IdleUSDT_BEST);
const idleTokenBestWBTC = new web3.eth.Contract(idleTokenABI, IdleWBTC_BEST);
const idleTokenBestWETH = new web3.eth.Contract(idleTokenABI, IdleWETH_BEST);

// Risk-Adjusted
const idleTokenRiskDAI = new web3.eth.Contract(idleTokenABI, IdleDAI_RISK);
const idleTokenRiskUSDC = new web3.eth.Contract(idleTokenABI, IdleUSDC_RISK);
const idleTokenRiskUSDT = new web3.eth.Contract(idleTokenABI, IdleUSDT_RISK);

const getDAI = async () => {
  try {
    const amount = "1000000000000000000";
    await idleTokenBestDAI.approve(IdleDAI_BEST, amount, { from: user });

    const res = idleTokenBestDAI.mintIdleToken(amount, true, user, {
      from: user,
    });
    console.log(res);
  } catch (error) {
    console.log(error);
  }
};

getDAI();
```
The error I got:
```

C:\Users\USER\Desktop\idle>node index.js
TypeError: idleTokenBestDAI.approve is not a function
    at getDAI (C:\Users\USER\Desktop\idle\index.js:42:28)
    at Object.<anonymous> (C:\Users\USER\Desktop\idle\index.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

```
What could be wrong?

**Comment by bugduino** [comment]
This line 
```    
await idleTokenBestDAI.approve(IdleDAI_BEST, amount, { from: user });
``` 
should instead be this 
```    
await DAI.approve(IdleDAI_BEST, amount, { from: user });
``` 
where `DAI` is the instance of the DAI contract on the network you are using.

Essentially you have to allow the idleToken contract to spend your DAI, not your idleDAI

**Comment by Sam-Devs** [comment]
I am confused.
What I did there was basically trying to specify the strategy by the token address.
Please be more explicit.

**Comment by bugduino** [comment]
You got this error `idleTokenBestDAI.approve is not a function` because you are trying to call `approve` on `idleDAI` contract, which is wrong because you have instead to call that `approve` method on the `DAI` contract. Please check the doc here https://developers.idle.finance/methods/mintidletoken

**Comment by Sam-Devs** [comment]
Okay, so basically I should be calling the approve function on the user token (DAI, USDC etc) not on the contract IdleDAI.

**Comment by bugduino** [comment]
Yes exactly

**Comment by Sam-Devs** [comment]
Thank you.
So I would have to get the addresses of the user tokens (DAI, USDC, etc) which would stand as the underlying asset for each of the supported tokens.
Would you mind sharing your social media profile?
Would like to send some DMs outside here.

**Comment by bugduino** [comment]
You can join our Idle Discord server here https://discord.gg/YBDBSXAH , we have a dedicated #dev-support channel
